-- Insert 2024 Grade 8 correct_answer and official_solution into gauss_source_questions

INSERT INTO gauss_source_questions (id, year, grade, question_number, correct_answer, official_solution)
VALUES
('waterloo_gauss_g8_2024_q01', 2024, 8, 1, 'E', 'The number of 5 cent coins needed to make 25 cents is 25 cents / 5 cents = 5.
Answer: (E)'),
('waterloo_gauss_g8_2024_q02', 2024, 8, 2, 'E', 'If a figure has a vertical line of symmetry, then when it is reflected in (or folded along) this vertical line, the two halves of the figure are identical to one another. Of the given shapes, such a vertical line is only possible for (E). Answer: (E)'),
('waterloo_gauss_g8_2024_q03', 2024, 8, 3, 'B', 'Of the given numbers, only 1.32 and 1.03 are greater than 1. Since the tenths digit of 1.32, namely 3, is greater than the tenths digit of 1.03, which is 0, then 1.32 is the largest number in the list. Answer: (B)'),
('waterloo_gauss_g8_2024_q04', 2024, 8, 4, 'D', 'If 50% of n is 2024, then half of n is 2024, and so n is equal to 2 times 2024, which is equal to 4048. (We may confirm that 50% of 4048, or half of 4048, is 2024 as required.) Answer: (D)'),
('waterloo_gauss_g8_2024_q05', 2024, 8, 5, 'D', 'Reading from the graph, Ryan ran 2 km on Monday, 4 km on Tuesday, 6 km on Wednesday, 5 km on Thursday, and 3 km on Friday. Thus, the total distance that Ryan ran over the five days is 2+4+6+5+3=20 km. Answer: (D)'),
('waterloo_gauss_g8_2024_q06', 2024, 8, 6, 'B', 'When 11 is increased by 2, the result is 13. When 13 is then multiplied by 3, the final result is 13 × 3 = 39. Answer: (B)'),
('waterloo_gauss_g8_2024_q07', 2024, 8, 7, 'B', 'If 15 + a = 10, then a = 10 − 15 and so a = −5.
Answer: (B)'),
('waterloo_gauss_g8_2024_q08', 2024, 8, 8, 'D', 'Since the measure of a straight angle is 180°, then 40° + x° + x° = 180°. Solving this equation, we get 40 + x + x = 180 or 2x = 140, and so x = 70.
Answer: (D)'),
('waterloo_gauss_g8_2024_q09', 2024, 8, 9, 'D', 'The ratio of the number of spoons to the number of forks is 1: 2, which means that for each spoon in the drawer, there are 2 forks in the drawer. That is, the spoons and forks in the drawer can be separated into groups of 3 (1 spoon and 2 forks), and thus the total number of spoons and forks in the drawer must be a multiple of 3. Each of the answers 12, 6, 18, and 3 is a multiple of 3. The only answer given that is not a multiple of 3 is 10, and so the total number of spoons and forks in the drawer cannot be 10. Answer: (D)'),
('waterloo_gauss_g8_2024_q10', 2024, 8, 10, 'C', 'The large square with side length 6 has area 6 × 6 = 36. The shaded squares with side lengths 3, 2 and 1, have areas 3 × 3 = 9, and 2 × 2 = 4, and 1 × 1 = 1, respectively. The total area of the shaded regions is 9 + 4 + 1 = 14. The total area of the unshaded region is equal to the area of the shaded regions subtracted from the area of the large square, or 36 − 14 = 22.
Answer: (C)'),
('waterloo_gauss_g8_2024_q11', 2024, 8, 11, 'E', 'Continuing the sequence, we get 1, 3, 4, 7, 11, 18, 29, 47, 76, 123, and so the smallest number greater than 100 that appears in the sequence is 123. Answer: (E)'),
('waterloo_gauss_g8_2024_q12', 2024, 8, 12, 'D', 'Since 385 has a units digit of 5, then it is divisible by 5. Dividing, we get 385 / 5 = 77. Since 77 = 7 × 11, then the three prime factors of 385 are 5, 7 and 11, and their sum is 5 + 7 + 11 = 23.
Answer: (D)'),
('waterloo_gauss_g8_2024_q13', 2024, 8, 13, 'C', 'We begin by splitting ABCD into three equilateral triangles, as shown. (Confirm for yourself that this is the only way to do this.) Since the equilateral triangle in the middle shares a side with each of the two other equilateral triangles, then the sides of all three equilateral triangles are equal in length. The perimeter of ABCD is made up of 5 side lengths of these equilateral triangles. Since the perimeter of ABCD is 840 cm, then each side length of these equilateral triangles is 840 cm / 5 = 168 cm. Since AB is a side of an equilateral triangle, then AB = 168 cm. Answer: (C)'),
('waterloo_gauss_g8_2024_q14', 2024, 8, 14, 'C', 'One container of ice cream can make 6 cones. Thus, 2 containers of ice cream can make 2 × 6 = 12 cones. Since 12 cones were made from 5 containers of ice cream, and it takes 2 containers of ice cream to make 12 cones, then 5 - 2 = 3 containers of ice cream remain after the 12 cones are made. One container of ice cream can make 4 sundaes. Thus, the remaining 3 containers of ice cream can make 3 × 4 = 12 sundaes. Answer: (C)'),
('waterloo_gauss_g8_2024_q15', 2024, 8, 15, 'D', 'Given that n has a remainder of 8 when divided by 10, then n is 8 more than a multiple of 10. This means that n has a units digit of 8, which is 3 more than a units digit of 5, and thus n has a remainder of 3 when divided by 5. We may confirm that examples of numbers that are equal to 8 more than a multiple of 10, such as 8, 18, 28, 38, do indeed leave a remainder of 3 when divided by 5. Answer: (D)'),
('waterloo_gauss_g8_2024_q16', 2024, 8, 16, 'A', 'Before the hole was drilled, the volume of the block of wood was 4 cm × 4 cm × 7 cm = 112 cm^3. The cylindrical hole has radius 1 cm and height equal to that of the block of wood, 7 cm. The volume of the cylindrical hole is thus π × (1 cm)^2 × 7 cm = 7π cm^3. In cm^3, the volume of the block of wood after the hole is drilled is 112 − 7π ≈ 90.01, which when rounded to the nearest cm^3, is 90 cm^3.
Answer: (A)'),
('waterloo_gauss_g8_2024_q17', 2024, 8, 17, 'C', 'There are 3 different colours and 4 different numbers, and therefore 3 × 4 = 12 different kinds of robots that may be assembled. (These are R1, R2, R3, R4, B1, B2, B3, B4, G1, G2, G3, G4, where R, B, G represent the 3 colours red, blue, green.) Since there are 12 different kinds of robots, it is possible that the first 12 robots assembled are all different from one another. In this case, the 13th robot assembled would be the first robot to have the same colour and the same number as a previously assembled robot, and thus the greatest possible value of n is 13. Answer: (C)'),
('waterloo_gauss_g8_2024_q18', 2024, 8, 18, 'C', 'The angle of one complete rotation measures 360°. Since the spinner is divided into 5 equal sections, each 360° / 5 = 72° rotation moves the arrow to the next dividing line between two sections. Rotating clockwise, the section labelled D is the 4th section. This means that if the angle of rotation is greater than 3 × 72° = 216° and less than 4 × 72° = 288°, then the arrow stops in the section labelled D. Since each of the given answers is greater than 360° and less than 720°, the arrow must have spun through more than one and less than two complete rotations. On the second spin around, the arrow will stop in the section labelled D if the angle of rotation is greater than 216° + 360° = 576° and less than 288° + 360° = 648°. Only one of the given answers lies in this range, and so the angle of rotation must be 630°. Answer: (C)'),
('waterloo_gauss_g8_2024_q19', 2024, 8, 19, 'E', 'Solution 1
In this solution, we work backward from each of the given choices. Since we are asked to find the smallest possible integer in the list, we begin with the smallest of the five choices, 39. If the smallest integer in the list is 39, then the largest integer in the list is 39 + 14 = 53 (since the three integers have a range of 14). If the three integers have a mean of 50, then they have a sum of 50 × 3 = 150. Two of the integers are 39 and 53, and so the third (the middle) integer is 150 − 39 − 53 = 58. Since 58 is greater than 53, this is not possible (the range of these three integers is 58 − 39 = 19, not 14). If the smallest integer in the list is 40 (the next smallest answer given), then the largest integer in the list is 40 + 14 = 54. If two of the integers are 40 and 54, then the third (the middle) integer is 150 − 40 − 54 = 56. Since 56 is greater than 54, this is not possible (the range of these three integers is 56 − 40 = 16, not 14). If the smallest integer in the list is 41 (the next smallest answer given), then the largest integer in the list is 41 + 14 = 55. If two of the integers are 41 and 55, then the third (the middle) integer is 150 − 41 − 55 = 54. We may confirm that the three integers 41, 54, 55 indeed have a range of 14 and a mean of 50. We have shown that 41 is the smallest of the five choices to satisfy the given conditions, and so 41 is the smallest possible integer in the list. Answer: (E)'),
('waterloo_gauss_g8_2024_q20', 2024, 8, 20, 'D', 'Since 21 pieces of fruit are not apples, then the number of pears added to the number of bananas is 21. Since 25 pieces of fruit are not pears, then the number of apples added to the number of bananas is 25. Since 28 pieces of fruit are not bananas, then the number of apples added to the number of pears is 28. In adding these three totals 21 + 25 + 28, we are counting the number of pears twice, the number of bananas twice, and the number of apples twice (since each appears in exactly two of the three statements above). That is, 21 + 25 + 28 = 74 is twice the total number of pieces of fruit, and so the number of pieces of fruit in the box is 74 / 2 = 37. Answer: (D)'),
('waterloo_gauss_g8_2024_q21', 2024, 8, 21, 'B', 'Expressing the product 6 × 5 × 4 × 3 × 2 × 1 in terms of prime factors, we get 6 × 5 × 4 × 3 × 2 × 1 = (2 × 3) × 5 × (2 × 2) × 3 × 2. This product has 4 factors of 2, 2 factors of 3, and 1 factor of 5, and thus is equal to 2^4 × 3^2 × 5^1. The value of a + b + c is 4 + 2 + 1 = 7.
Answer: (B)'),
('waterloo_gauss_g8_2024_q22', 2024, 8, 22, 'C', 'The ratio of the number of quarters to the number of dimes to the number of nickels is 9 : 3 : 2. This means that for some positive integer k, the number of quarters is 9k, the number of dimes is 3k, and the number of nickels is 2k. The value of each quarter is 0.25 or 25 cents, and so the value of the quarters in the jar, in cents, is 25 × 9k = 225k. The value of each dime is 0.10 or 10 cents, and so the value of the dimes in the jar, in cents, is 10 × 3k = 30k. The total value of the quarters and dimes is 17.85 or 1785 cents, and so 225k + 30k = 1785 or 255k = 1785, and so k = 1785 / 255 = 7. The number of nickels is 2k = 14, and so the value of the nickels is 0.05 × 14 = 0.70. Answer: (C)'),
('waterloo_gauss_g8_2024_q23', 2024, 8, 23, 'B', 'The smallest five positive integers, each having a divisor of d, are d, 2d, 3d, 4d, and 5d. Thus, the smallest possible sum of five different positive integers whose greatest common divisor is d is d + 2d + 3d + 4d + 5d = 15d. We know that the sum is at least 15d and is equal to 264, which means that 15d ≤ 264, and so d ≤ 264 / 15 or d ≤ 17.6. Each of the five integers is divisible by d, and so the sum of the five integers, 264, is divisible by d. Thus, we want the largest possible divisor of 264 that is less than or equal to 17. Since 264 = 2^3 × 3 × 11, the divisors of 264 that are less than or equal to 17 are: 1, 2, 3, 4, 6, 8, 11, and 12, and so the largest possible value of d is 12. The sum of the digits of the largest possible value of d is 1 + 2 = 3.
Answer: (B)'),
('waterloo_gauss_g8_2024_q24', 2024, 8, 24, 'A', 'There are 6 different locations at which the path splits, and we label these splits 1 to 6, as shown. We begin by determining the probability that a ball lands in the bin labelled A. There is exactly one path that leads to bin A. This path travels downward to the left at each of the three splits labelled 1, 2 and 3. At each of these splits, the probability that a ball travels to the left is 1/2, and so the probability that a ball lands in bin A is 1/2 × 1/2 × 1/2 = 1/8. Next, we determine the probability that a ball lands in the bin labelled C. There are exactly three paths that lead to bin C. One of these paths travels downward to the right at each of the three splits labelled 1, 4 and 6. Thus, the probability that a ball lands in bin C by following this path is 1/2 × 1/2 × 1/2 = 1/8. A second path to bin C travels downward to the right at split 1, to the left at split 4, to the right at split 5, and to the right at split 6. The probability that a ball follows this path is 1/2 × 1/2 × 1/2 × 1/2 = 1/16. The third and final path to bin C travels left at split 1, and to the right at each of the three splits 2, 5 and 6. The probability that a ball follows this path is also 1/16. The probability that a ball lands in bin C is the sum of the probabilities of travelling each of these three paths or 1/8 + 1/16 + 1/16 = 2/16 + 1/16 + 1/16 = 4/16 = 1/4 Finally, we determine the probability that a ball lands in bin B. The probability that it lands in bin B is 1 minus the probability that it lands in bin A minus the probability that it lands in bin C, or 1 − 1/8 − 1/4 = 8/8 − 1/8 − 2/8 = 5/8 The probability that the two balls land in different bins is equal to 1 minus the probability that the two balls land in the same bin. The probability that a ball lands in bin A is 1/8, and so the probability that two balls land in bin A is 1/8 × 1/8 = 1/64. The probability that a ball lands in bin C is 1/4, and so the probability that two balls land in bin C is 1/4 × 1/4 = 1/16. The probability that a ball lands in bin B is 5/8, and so the probability that two balls land in bin B is 5/8 × 5/8 = 25/64. Therefore, the probability that the two balls land in different bins is equal to 1 − 1/64 − 1/16 − 25/64 = 64/64 − 1/64 − 4/64 − 25/64 = 34/64 = 17/32 Answer: (A)'),
('waterloo_gauss_g8_2024_q25', 2024, 8, 25, 'B', 'The smallest possible value of d is closest to 6.40. On a flat surface, the shortest distance between two points is along a straight line between the points. The ant must walk on the surface of the figure, and so to determine a straight line distance between P and Q, we can "flatten" the figure. To determine the length of P Q, we position R so that P R is perpendicular to QR, as shown below. Triangle P QR is a right-angled triangle with P R = 5 and QR = 4, and so by the Pythagorean Theorem, we get PQ = sqrt(5^2 + 4^2) = sqrt(41), and so the distance d is closest to 6.40. Since 6.40 is the smallest of the five choices given, and we have shown that there is a path of this length from P to Q on the figure''s surface, then the smallest possible value of d is 6.40. Answer: (B)');
