-- Update 2025 Grade 8 questions with correct_answer and official_solution
-- Run this AFTER inserting the questions from insert_2025_g8_source_questions.sql

UPDATE gauss_source_questions SET correct_answer = 'B', official_solution = 'In each row, exactly 3 of the 6 or one-half of the circles are shaded. Thus, one-half of the 24, that is, 12 circles are shaded. Alternately, we could just count the 12 shaded circles. Answer: (B)' WHERE year = 2025 AND grade = 8 AND question_number = 1;

UPDATE gauss_source_questions SET correct_answer = 'D', official_solution = 'If each of 4 children shared 36 pieces equally, then each child received 36 / 4 = 9 pieces. Answer: (D)' WHERE year = 2025 AND grade = 8 AND question_number = 2;

UPDATE gauss_source_questions SET correct_answer = 'D', official_solution = 'There are 7 days in each week, and so there are 2 × 7 = 14 days in two weeks. Thus, the date two weeks from May 12 is May 26 (since 12 + 14 = 26). Answer: (D)' WHERE year = 2025 AND grade = 8 AND question_number = 3;

UPDATE gauss_source_questions SET correct_answer = 'C', official_solution = 'Solution 1
The time 2 hours after 8:45 a.m. is 10:45 a.m., and the time 45 minutes after 10:45 a.m. is 11:30 a.m.

Solution 2
Two hours and 45 minutes is 15 minutes less than 3 hours. The time 3 hours after 8:45 a.m. is 11:45 a.m., and the time 15 minutes before 11:45 a.m. is 11:30 a.m.
Answer: (C)' WHERE year = 2025 AND grade = 8 AND question_number = 4;

UPDATE gauss_source_questions SET correct_answer = 'A', official_solution = 'If 7x - 3 = 60, then 7x = 60 + 3, so 7x = 63 and x = 63 / 7 = 9. Answer: (A)' WHERE year = 2025 AND grade = 8 AND question_number = 5;

UPDATE gauss_source_questions SET correct_answer = 'D', official_solution = 'There are 2 ways to colour the triangle and 3 ways to colour the square, and so there are 2 × 3 = 6 ways to colour the figure. We can write the 6 colourings of the figure as ordered pairs in which the first colour listed in the pair is the colour of the triangle and the second is the colour of the square. These are: (red, blue), (red, purple), (red, green), (yellow, blue), (yellow, purple), and (yellow, green). Answer: (D)' WHERE year = 2025 AND grade = 8 AND question_number = 6;

UPDATE gauss_source_questions SET correct_answer = 'A', official_solution = 'When the point (5, 7) is reflected in the x-axis, the resulting point is (5, -7). When a point is reflected in the x-axis, its x-coordinate does not change and its y-coordinate changes sign (provided that the original point is not on the x-axis). Answer: (A)' WHERE year = 2025 AND grade = 8 AND question_number = 7;

UPDATE gauss_source_questions SET correct_answer = 'D', official_solution = 'Reading from the graph, 5 students voted for Spring, 15 voted for Summer, 5 voted for Fall, and 10 voted for Winter. Therefore, (A) Fall and Spring received the same number of votes, (B) Winter received more votes than Spring, (C) 35 students participated in the survey, and (E) 5 students voted for Fall, are all true statements. Since 15 students voted for Summer and 15 is less than half of 35, then (D) is the statement that is false. Answer: (D)' WHERE year = 2025 AND grade = 8 AND question_number = 8;

UPDATE gauss_source_questions SET correct_answer = 'D', official_solution = 'Solution 1
The sum of the original five digits is 5 + 2 + 8 + 7 + 9 = 31. The largest multiple of 4 that is less than 31 is 28, and 28 is 3 less than 31. However, 3 is not among the list of five digits, and thus Ruhab cannot erase a 3. The next largest multiple of 4 that is less than 31 is 24. Since 31 - 24 = 7, and 7 does appear in the original list of five digits, then if Ruhab erases the 7, the sum of the remaining four digits is a multiple of 4. (We may confirm that 5 + 2 + 8 + 9 = 24.)

Solution 2
We may erase each of the five digits one at a time and in each case, determine the sum of the remaining four digits. Doing so, we get 5 + 2 + 8 + 7 = 22; 5 + 2 + 8 + 9 = 24; 5 + 2 + 7 + 9 = 23; 5 + 8 + 7 + 9 = 29; 2 + 8 + 7 + 9 = 26. Of these sums, only 24 is a multiple of 4 and so Ruhab erased the digit 7. Answer: (D)' WHERE year = 2025 AND grade = 8 AND question_number = 9;

UPDATE gauss_source_questions SET correct_answer = 'C', official_solution = 'The perfect squares are 1^2 = 1, 2^2 = 4, 3^2 = 9, and so on. There are 18 integers between 3 and 20 inclusive. Of these 18 integers, only 2^2 = 4, 3^2 = 9 and 4^2 = 16 are perfect squares. (We note that 1^2 = 1 and 5^2 = 25 are not among the integers given.) The probability of randomly selecting a perfect square from the integers given is 3 / 18 = 1 / 6. Answer: (C)' WHERE year = 2025 AND grade = 8 AND question_number = 10;

UPDATE gauss_source_questions SET correct_answer = 'E', official_solution = 'Since 28/32 + 1/box = 1 and 28/32 + 4/32 = 32/32 = 1, then 1/box = 4/32. Reducing 4/32 to lowest terms, we get 4/32 = 1/8, and so the number that goes in the box is 8. Answer: (E)' WHERE year = 2025 AND grade = 8 AND question_number = 11;

UPDATE gauss_source_questions SET correct_answer = 'A', official_solution = 'There are 60 minutes in one hour. Since 3 × 20 minutes = 60 minutes, and 3 × 1.5 km = 4.5 km, then Leticia can walk 4.5 km in one hour. Walking at this same rate, Leticia can walk 4 × 4.5 km = 18 km in 4 hours. Answer: (A)' WHERE year = 2025 AND grade = 8 AND question_number = 12;

UPDATE gauss_source_questions SET correct_answer = 'D', official_solution = 'Ordered from smallest to largest, the list is 1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6. This list contains 1 + 2 + 3 + 4 + 5 + 6 = 21 integers. The median is the middle number in an ascending (or descending) list of numbers. The 11th integer in the list of 21 integers above has 10 integers before it and 10 integers following it, and thus is the median of the list. The 11th integer and the median of the given list is 5. Answer: (D)' WHERE year = 2025 AND grade = 8 AND question_number = 13;

UPDATE gauss_source_questions SET correct_answer = 'D', official_solution = 'Opposite angles are equal in measure and so t = 50° since it is opposite the angle whose measure is given as 50°. By a property of parallel lines, the angles whose measures are t and x form a "C pattern", and are supplementary. Thus t + x = 180° or x = 180° - 50° = 130°. Since the angle whose measure is y is opposite the angle whose measure is x, then y = x = 130°. Since t + y = 50° + 130° = 180°, then from the given answers, t and y are the pair of angles whose measures sum to 180°. Of the answers given, we confirm that no other pair of angles have measures whose sum is 180° by determining the measures of each of the missing angles, as shown. Answer: (D)' WHERE year = 2025 AND grade = 8 AND question_number = 14;

UPDATE gauss_source_questions SET correct_answer = 'E', official_solution = 'Solution 1
The mean age of the first three students is 13, and so the sum of their ages is 13 × 3 = 39. The mean age of the four students is 14, and so the sum of their ages is 14 × 4 = 56. The age of the fourth student is the difference between these two sums, which is 56 - 39 = 17 years old.

Solution 2
In an ordered list of 3 consecutive integers, the average of the list is always the middle integer. Can you see why? Therefore, three students whose ages are consecutive integers and whose mean age is 13 are 12, 13 and 14 years old. Suppose the fourth student is x years of age. Since the mean age of the four students is 14, then (12 + 13 + 14 + x) / 4 = 14 or 39 + x = 14 × 4, and so x = 56 - 39 = 17. The fourth student is 17 years old. Answer: (E)' WHERE year = 2025 AND grade = 8 AND question_number = 15;

UPDATE gauss_source_questions SET correct_answer = 'C', official_solution = 'There is 1 dog for every bowl of food, and so if there were 6 dogs, then there would be 6 bowls of food. There are 2 dogs for every bowl of water, and so these same 6 dogs would need 6 / 2 = 3 bowls of water. There are 3 dogs for every bowl of treats, and so the 6 dogs would need 6 / 3 = 2 bowls of treats. Thus, 6 dogs require 6 bowls of food, 3 bowls of water, and 2 bowls of treats, or 6 + 3 + 2 = 11 bowls in total. There are 11 bowls for every 6 dogs, and since there are 77 = 11 × 7 bowls, then there are 7 groups of 6 dogs, or 6 × 7 = 42 dogs. Answer: (C)' WHERE year = 2025 AND grade = 8 AND question_number = 16;

UPDATE gauss_source_questions SET correct_answer = 'B', official_solution = 'In triangle CBD, CB = BD and so ∠BCD and ∠BDC have equal measures. The sum of the angles in a triangle is 180°, and since ∠CBD = 90°, then ∠BCD = ∠BDC = 45°. (We confirm that 90° + 45° + 45° = 180°.) Since ∠CDE is a straight angle, then ∠BDE + ∠BDC = 180° or ∠BDE = 180° - 45° = 135°. In triangle BDE, BD = DE and so ∠DBE and ∠DEB have equal measures. The sum of the angles in a triangle is 180°, and since ∠BDE = 135°, then ∠DBE = (180° - 135°) / 2 = 22.5°. Finally, since ∠ABC is a straight angle, then ∠ABE + ∠DBE + ∠DBC = 180° or ∠ABE = 180° - 22.5° - 90° = 67.5°. Answer: (B)' WHERE year = 2025 AND grade = 8 AND question_number = 17;

UPDATE gauss_source_questions SET correct_answer = 'B', official_solution = 'In the grid shown, the first column and first row show the possible numbers that may appear on the top faces of the two dice. The inside of the grid shows the product of the corresponding two numbers. Of the results, a product of 4 appears 3 times, a product of 6 appears 4 times, a product of 9 appears 1 time, a product of 15 appears 2 times, and a product of 8 appears 2 times. Thus, of the possible products given, 6 is the most likely to occur. Answer: (B)' WHERE year = 2025 AND grade = 8 AND question_number = 18;

UPDATE gauss_source_questions SET correct_answer = 'E', official_solution = 'We begin by determining the prime factorization of 2025. 2025 = 25 × 81 = 5 × 5 × 9 × 9 = 5 × 5 × 3 × 3 × 3 × 3 = 3^4 × 5^2. There are exactly 15 positive factors of 2025. These are: 1, 3, 3^2, 3^3, 3^4, 5, 5^2, 3 × 5, 3^2 × 5, 3^3 × 5, 3^4 × 5, 3 × 5^2, 3^2 × 5^2, 3^3 × 5^2, and 3^4 × 5^2. We are asked to express 2025 as the product of two positive integers n and m^2, where m^2 is a perfect square. Of the 15 positive factors, the following are perfect squares: 1, 3^2, 3^4, 5^2, 3^2 × 5^2, and 3^4 × 5^2. These are all the possible values of m^2, and so the values of m are: 1, 3, 5, 3^2, 3 × 5, and 3^2 × 5. Thus, the ordered pairs of positive integers (m, n) for which m^2 × n = 2025 are: (1, 3^4 × 5^2), (3, 3^2 × 5^2), (5, 3^4), (3^2, 5^2), (3 × 5, 3^2), (3^2 × 5, 1). Therefore, there are 6 such ordered pairs. Answer: (E)' WHERE year = 2025 AND grade = 8 AND question_number = 19;

UPDATE gauss_source_questions SET correct_answer = 'B', official_solution = 'In the first diagram shown, we label the vertices of the polygon and the length ST = c, since ST = QR. Next, we extend UT by a length equal to SR, and we extend QR by a length equal to ST, as shown in the second diagram. Each of the angles in the polygon is a right angle, and so these two extended line segments are perpendicular to each other and will meet at a point that we label V. That is, STVR is a rectangle with TV = SR = b and RV = ST = c. Each of the following expressions is equal to the perimeter of the original polygon: PQ + QR + SR + ST + TU + PU = PQ + QR + ST + SR + TU + PU (reordering the lengths) = PQ + QR + RV + TV + TU + PU (since RV = ST and TV = SR) = PQ + QV + UV + PU (since QR + RV = QV and TV + TU = UV) which is the perimeter of PQVU. Each of the angles in PQVU is a right angle, and PQ = PU, and thus PQVU is a square. Since PQ = UV = UT + TV = a + b, and PU = QV = QR + RV = c + c = 2c, then a + b = 2c. The perimeter of the original polygon is equal to the perimeter of square PQVU, and each side length of square PQVU can be expressed as a + b or as 2c since a + b = 2c. Of the expressions given, a + b + 7c = 2c + 7c = 9c is not equal to the perimeter, then the correct answer is (B). Answer: (B)' WHERE year = 2025 AND grade = 8 AND question_number = 20;

UPDATE gauss_source_questions SET correct_answer = 'A', official_solution = 'H is a perfect square and is 1 more than D. The perfect squares from 1 to 8 inclusive are 1 and 4. Since H is one more than D, H cannot be equal to 1 (since D ≠ 0), and so H = 4 and D = 3. B is the largest prime number in the set, and so B = 7. C is a multiple of both G and D. Since D = 3, then C = 6 and G is equal to either 1 or 2 (since 6 is a multiple of each of these). The value of B + G is even, and since B = 7, then G = 1. The letters which have not been assigned values are A, E and F, and the integers which have not been assigned are 2, 5 and 8. Since 5 and 8 are in the same row and A and E are the two remaining unassigned letters that are in the same row, then A and E are 5 and 8 in some order, which leaves F = 2. Answer: (A)' WHERE year = 2025 AND grade = 8 AND question_number = 21;

UPDATE gauss_source_questions SET correct_answer = 'B', official_solution = 'The opposite sides of ABCD are parallel, and so ABCD is a parallelogram. The opposite sides of a parallelogram are equal in length, and so AB = CD and AD = BC. Since the value of r + s + t is equal to a constant, we may choose any location for B(0, r) provided that it satisfies the given condition r < 0. We choose r = -2, so that the y-coordinate of B(0, r) is equal to the y-coordinate of A(-3, -2), and so AB is a horizontal line segment. In this case, the length of AB is equal to the positive difference between the x-coordinates of A and B, which is 0 - (-3) = 3. CD is parallel to AB, and so CD must also be a horizontal line segment. Thus, points C(6, 10) and D(s, t) have equal y-coordinates, and so t = 10. Further, CD has the same length as AB, and so 6 - s = 3 or s = 3. Therefore, the value of r + s + t = -2 + 3 + 10 = 11. Answer: (B)' WHERE year = 2025 AND grade = 8 AND question_number = 22;

UPDATE gauss_source_questions SET correct_answer = 'E', official_solution = 'Let the last three digits of n be abc. That is, n has units digit c, tens digit b and hundreds digit a. The units digit of the product 2013 × n is equal to the units digit of 3 × c. Since the units digit of the product 2013 × n is 5, then the units digit of 3 × c is 5, and so c = 5. Continuing the long multiplication, the tens digit of n is b, and so the tens digit of 2013 × n is equal to the units digit of 6 + 3b. Since the units digit of 6 + 3b is 2, then the units digit of 3b is 6, and so b = 2. We have determined that the last two digits of the product 2013 × n are 25 exactly when the last two digits of n are 25. Continuing the long multiplication, the hundreds digit of n is a, and so the hundreds digit of 2013 × n is equal to the units digit of 1 + 0 + 2 + 3a. Since the units digit of 3 + 3a is 0, then the units digit of 3a is 7, and so a = 9. The last three digits of 2013 × n are 025 exactly when the last three digits of n are 925. Thus, the smallest possible value of n for which 2013 × n has last four digits 2025, is n = 925, and so the sum of the digits of n is 9 + 2 + 5 = 16. Answer: (E)' WHERE year = 2025 AND grade = 8 AND question_number = 23;

UPDATE gauss_source_questions SET correct_answer = 'E', official_solution = 'Suppose the integer in the centre circle is a. Then each integer in a circle connected to the centre circle is either d more than a, which is a + d, or it is d less than a, which is a - d. Through systematic analysis of all cases, we determine that d can be equal to each of the first 20 positive integers with the exception of 5, 10, 15, and 20, and so there are 20 - 4 = 16 different possible values of d. Answer: (E)' WHERE year = 2025 AND grade = 8 AND question_number = 24;

UPDATE gauss_source_questions SET correct_answer = 'B', official_solution = 'We begin by recognizing that in the given list, each of the digits 1 through 7 occurs at least once as a units digit, and at least once as a tens digit. The units digit of each number in the list matches the tens digit of the number that follows it. Through systematic analysis, we determine that the tens digit of the first number must be 1, and the units digit of the last number must be 4. There are 2 different ways to arrange the numbers in list A, 12 different ways to arrange the numbers in list B, and exactly 1 way to place the number 14 between arrangements of each of the two lists. Thus, the total number of arrangements of the given list is 2 × 12 × 1 = 24. Answer: (B)' WHERE year = 2025 AND grade = 8 AND question_number = 25;
